#!/bin/bash

# 🚀 Voice Changer 免费部署向导

echo "=========================================="
echo "  Voice Changer 免费部署方案选择"
echo "=========================================="
echo ""
echo "选择你的部署方案："
echo ""
echo "1️⃣  Vercel + Render（推荐，5分钟上线）"
echo "2️⃣  Oracle Cloud（永久免费，30分钟）"
echo "3️⃣  本地 + Cloudflare Tunnel（2分钟）"
echo "4️⃣  Docker 本地运行"
echo "5️⃣  查看详细文档"
echo ""
read -p "请选择 (1-5): " choice

case $choice in
    1)
        echo ""
        echo "📌 Vercel + Render 部署步骤："
        echo ""
        echo "【第1步】上传到 GitHub"
        echo "  git add ."
        echo "  git commit -m 'Deploy to Vercel + Render'"
        echo "  git push origin main"
        echo ""
        echo "【第2步】前端部署到 Vercel"
        echo "  1. 访问 https://vercel.com"
        echo "  2. 用 GitHub 账号登录"
        echo "  3. New Project > 选择你的仓库"
        echo "  4. Framework: Other"
        echo "  5. Build Command: cd frontend && npm run build"
        echo "  6. Output Directory: frontend/dist"
        echo "  7. 点击 Deploy"
        echo ""
        echo "【第3步】后端部署到 Render"
        echo "  1. 访问 https://render.com"
        echo "  2. 点击 New > Web Service"
        echo "  3. 连接你的 GitHub 仓库"
        echo "  4. Start Command:"
        echo "     gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 app.main:app"
        echo "  5. 环境变量: PYTHONUNBUFFERED=1"
        echo "  6. Plan 选择 Free，点击 Create"
        echo ""
        echo "【第4步】配置环保变量"
        echo "  在 Vercel 环境变量中添加:"
        echo "  VITE_API_BASE_URL=https://your-render-app.onrender.com"
        echo ""
        echo "✅ 完成！5 分钟后访问你的 Vercel URL"
        echo ""
        ;;
    2)
        echo ""
        echo "📌 Oracle Cloud 免费部署步骤："
        echo ""
        echo "【第1步】注册 Oracle Cloud"
        echo "  访问: https://www.oracle.com/cloud/free/"
        echo "  需要信用卡验证（不会扣费）"
        echo ""
        echo "【第2步】创建虚拟机"
        echo "  - Region: 选择离你最近的区域"
        echo "  - Image: Ubuntu 22.04"
        echo "  - Shape: Ampere A1（永久免费）"
        echo "  - Public IP: 勾选"
        echo ""
        echo "【第3步】SSH 连接"
        echo "  ssh ubuntu@your-oracle-ip -i ~/your-key.key"
        echo ""
        echo "【第4步】安装 Docker 和部署"
        echo "  curl -fsSL https://get.docker.com | sh"
        echo "  sudo usermod -aG docker ubuntu"
        echo "  git clone https://github.com/your-username/voice-changer.git"
        echo "  cd voice-changer && docker-compose up -d"
        echo ""
        echo "【第5步】配置防火墙"
        echo "  Oracle Cloud Console > VNIC > 安全列表"
        echo "  添加 Ingress Rule: TCP 8000, 80, 443"
        echo ""
        echo "✅ 完成！访问 http://your-oracle-ip:8000"
        echo ""
        ;;
    3)
        echo ""
        echo "📌 本地 + Cloudflare Tunnel 部署步骤："
        echo ""
        echo "【第1步】安装 Cloudflare"
        echo "  macOS: brew install cloudflare/cloudflare-go/cloudflared"
        echo "  Linux: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
        echo ""
        echo "【第2步】启动后端"
        echo "  cd /Users/noizer/voice-changer"
        echo "  uvicorn app.main:app --port 8000"
        echo ""
        echo "【第3步】在另一个终端启动隧道"
        echo "  cloudflared tunnel --url http://localhost:8000"
        echo ""
        echo "【第4步】记下生成的 URL"
        echo "  类似: https://abc123.trycloudflare.com"
        echo ""
        echo "【第5步】启动前端"
        echo "  cd frontend"
        echo "  VITE_API_BASE_URL=https://abc123.trycloudflare.com npm run dev"
        echo ""
        echo "✅ 完成！别人可以通过生成的 URL 访问"
        echo ""
        ;;
    4)
        echo ""
        echo "📌 Docker 本地运行："
        echo ""
        echo "cd /Users/noizer/voice-changer"
        echo "./deploy.sh"
        echo ""
        echo "然后访问 http://localhost:8000"
        echo ""
        ;;
    5)
        echo ""
        echo "📖 查看详细文档..."
        echo ""
        echo "【完整免费部署指南】"
        echo "  cat /Users/noizer/voice-changer/FREE_DEPLOYMENT.md"
        echo ""
        echo "【部署常见问题】"
        echo "  cat /Users/noizer/voice-changer/DEPLOYMENT.md"
        echo ""
        ;;
    *)
        echo "❌ 无效的选择"
        exit 1
        ;;
esac

echo ""
echo "💡 需要帮助？查看完整文档："
echo "   FREE_DEPLOYMENT.md  - 免费部署方案"
echo "   DEPLOYMENT.md       - 所有部署方案"
